name: Update visual regression test screenshots

on:
  issue_comment:
    types: [created]

jobs:
  update_screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: ./.github/command
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}