name: Pretty cool

on:
  issue_comment:
    types: [created]

jobs:
  update_screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: theisgroenbech/pr-command@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pr-comment: "!pr pretty cool"
        run: |
          echo "hi2" >> hi.txt
          echo "hi3" >> hi.txt
        commit-message: Pretty cool commit