name: Update visual regression test screenshots

on:
  issue_comment:
    types: [created]

jobs:
  update_screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: ./.github/command
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_COMMENT: "!pr pretty cool"
        BASH_COMMAND: |
          echo "hi2" >> hi.txt
          echo "hi3" >> hi.txt
        COMMIT_MESSAGE: Pretty cool commit