name: Pretty cool

on:
  issue_comment:
    types: [created]

jobs:
  update_screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: ./.github/command
      with:
        token: ${{ secrets.PAT_TOKEN }}
        pr-comment: "!pr pretty cool"
#        run: |
#          echo "hi2" >> hi.txt
#          echo "hi3" >> hi.txt
#        write-comment: "Hi there 👋 \n\n You have the following options: \n - `!pr help`"
#        commit-message: Pretty cool commit